# Generated by Django 3.2 on 2022-03-14 14:16

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(help_text='Only video files are allowed.', upload_to='video/', validators=[videos.models.validate_video]),
        ),
    ]
