version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "chmod +x ./wait-for-postgres.sh && ./wait-for-postgres.sh db 5432 && python manage.py collectstatic --no-input && python manage.py migrate && gunicorn -w 2 video_manager.wsgi -b 0.0.0.0:8000"
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    restart: always

  db:
    image: postgres:14.0
    restart: always
    env_file:
      - ./.env
    volumes:
      - .dbdata:/var/lib/postgresql/data
      - .data:/data

